name: ai_research
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6.5
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - psycopg2
  - toolz
  - geopandas
  - altair
  - selenium
  # Put any conda dependencies here

  - pip:
    # Put any pip dependencies here (and no conda ones anywhere below)

  # Tooling requirements (don't edit)
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
    - webdriver-manager
    - altair_saver
    - fuzzywuzzy
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
